<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

do_action( 'genesis_doctype' );
do_action( 'genesis_title' );
do_action( 'genesis_meta' );

wp_head(); //* we need this for plugins
?>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>

<!-- Woven DFP Main Init -->
<script type='text/javascript'>
var googletag = googletag || {};
googletag.cmd = googletag.cmd || [];
(function() {
var gads = document.createElement('script');
gads.async = true;
gads.type = 'text/javascript';
var useSSL = 'https:' == document.location.protocol;
gads.src = (useSSL ? 'https:' : 'http:') + 
'//www.googletagservices.com/tag/js/gpt.js';
var node = document.getElementsByTagName('script')[0];
node.parentNode.insertBefore(gads, node);
})();
</script>

<script src="//www.googletagservices.com/tag/js/gpt.js"></script>


<!--DFP Conditional Header Switch-->
<?php include_once( 'wp-content/themes/genesis/DFP/category-init-headers/dfp-init.php'); ?>	

 

<!-- End Skin Tag Section //////////////////////// -->

</head>
<?php
genesis_markup( array(
	'html5'   => '<body %s>',
	'xhtml'   => sprintf( '<body class="%s">', implode( ' ', get_body_class() ) ),
	'context' => 'body',
) );
do_action( 'genesis_before' ); ?>

<!-- sumith -->
<script>
//STICKY NAV
$(document).ready(function () {  
 		  
		  $(window).scroll(function() {
				
 				var posFromTop = $(window).scrollTop();
				if(posFromTop > 80){ 
					$('.homeBar').stop().animate({opacity: 1}, 200);
					$('.homeBar').css('z-index',999);   
				} else { 
					$('.homeBar').stop().animate({opacity: 0}, 200);
					//$('.homeBar').css('z-index',-9);
				}
				 
 		   }); 
});
</script> 
 <?php if(is_home() || is_front_page()) { ?>
 	
	<div class="homeBar topBar">
		<div class="inner group">
			
			<div class="logo">
				<a href="/"></a>
			</div>
			
			<div class="share-box group">
				<span class="descrip fb">Like Us</span>
				<div class="share-btn">
                    <div id="fb-root"></div>
                        <script>(function(d, s, id) {
                          var js, fjs = d.getElementsByTagName(s)[0];
                          if (d.getElementById(id)) return;
                          js = d.createElement(s); js.id = id;
                          js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=101574723387224";
                          fjs.parentNode.insertBefore(js, fjs);
                        }(document, 'script', 'facebook-jssdk'));</script>
                        <div class="fb-like" data-href="https://www.facebook.com/NiceKicks" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"></div>
                    </div>
			</div>
			
			<div class="share-box group">
				<span class="descrip tw">Follow Us</span>
				<div class="share-btn">
    				
                    <a href="https://twitter.com/nicekicks" class="twitter-follow-button external" data-show-count="true" data-show-screen-name="false" target="_blank">Follow @nicekicks</a>
					<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
				
                </div>
			</div>
			
			<div class="share-box group">
				<span class="descrip gp">Circle Us</span>
				<div class="share-btn">
					<div class="g-plusone" data-size="medium" data-href="http://www.nicekicks.com/"></div>
				</div>
			</div>
			
		</div><!-- end inner group -->
</div>

<?php } else { ?>
	<div class="homeBar topBar">
		<div class="inner group">
			
			<div class="logo">
				<a href="/"></a>
			</div>
			
			<div class="share-box group">
				<span class="descrip fb">Share on Facebook</span>
				<div class="share-btn">
                     <div id="fb-root"></div>
						<script>(function(d, s, id) {
                          var js, fjs = d.getElementsByTagName(s)[0];
                          if (d.getElementById(id)) return;
                          js = d.createElement(s); js.id = id;
                          js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=101574723387224";
                          fjs.parentNode.insertBefore(js, fjs);
                        }(document, 'script', 'facebook-jssdk'));</script>
                        <div class="fb-share-button" data-href="" data-type="button_count"></div>
                </div>
			</div>
			
			<div class="share-box group">
				<span class="descrip tw">Share on Twitter</span>
				<div class="share-btn">
    				<a href="<?php echo $_SERVER['REQUEST_URI'];?>" class="twitter-share-button" data-lang="en">Tweet</a>
                </div>
			</div>
			
			<div class="share-box group">
				<span class="descrip gp">Share on Google+</span>
				<div class="share-btn">
					<div class="g-plusone" data-size="medium" data-href="<?php echo $_SERVER['REQUEST_URI'];?>"></div>
				</div>
			</div>
			
		</div><!-- end inner group -->
</div>


<?php } ?>

<!-- end -->


<?php
get_post_type();

genesis_markup( array(
	'html5'   => '<div %s>',
	'xhtml'   => '<div id="wrap">',
	'context' => 'site-container',
) );

do_action( 'genesis_before_header' );
do_action( 'genesis_header' );
do_action( 'genesis_after_header' );
?>

<!-- Woven Skin -->
<?php include_once( 'wp-content/themes/genesis/DFP/ad-skin.php'); ?>	
<!--.end Woven Skin -->


<!--.begin Woven pushdown -->
<?php

include ('wp-content/themes/genesis/DFP/ad-pushdown.php'); ?>
<!--.begin Woven pushdown -->

<!--.begin Woven 728x90 -->
<?php include_once('wp-content/themes/genesis/DFP/ad-728x90_TOP.php'); // Conditional logic is housed in the DFP files ?>
<!--.end Woven 728x90 Top -->
	<?php


genesis_markup( array(
	'html5'   => '<div %s>',
	'xhtml'   => '<div id="inner">',
	'context' => 'site-inner',
) );
genesis_structural_wrap( 'site-inner' );
