<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

do_action( 'genesis_doctype' );
do_action( 'genesis_title' );
do_action( 'genesis_meta' );

wp_head(); //* we need this for plugins
?>

<!--Adidas Test -->
<script>
        var ad_background='#FFFFFF',//Background Color
        ad_creative='http://nicekicks.com/wp-content/themes/nicekicks/images/ads/skins/LITE_Skin_NiceKicks.jpg', //Background URL
        ad_click_url='http://ad.doubleclick.net/clk;278602113;105830230;n', //Click URL
        ad_padding_top='0',//Top Padding.
        //<![CDATA[
        ord=Math.random()*10000000000000000;
        document.write('<img src="http://ad.doubleclick.net/ad/N5865.284182.WOVENDIGITAL/B7971430.13;sz=1x1;ord=' + ord + '?"/>');
        //]]>
        document.write('<style>');
        document.write('body{background:'+ad_background+' url('+ad_creative+')center top no-repeat!important; padding-top:'+ad_padding_top+'px!important;}');
        //document.write('#header, #wrap{position:relative;z-index:10;}');
        document.write('#bglink_left{margin-left:-700px;display: block;height: 100%;width: 200px;position: fixed;left: 50%;top: 0;z-index: 1000;text-indent:-5000em;}');
        document.write('#bglink_right{margin-left: 500px;display: block;height: 100%;width: 200px;position: fixed;left: 50%;top: 0;z-index: 1000;text-indent:-5000em;}');
        document.write('#bglink_top{display: block;height: 150px;width: 100%;position: absolute;top: 0;z-index: 0;text-indent:-5000em;}');
            document.write('#container{margin-top:0px;}');
        document.write('</style>');
        document.write('<a href="'+ad_click_url+'" target="_blank" id="bglink_top"></a>');
        document.write('<a href="'+ad_click_url+'" target="_blank" id="bglink_left"></a>');
        document.write('<a href="'+ad_click_url+'" target="_blank" id="bglink_right"></a>');
</script>
<style>/*
    .mainHeader { padding:0px 0 0!important;}
    .container{margin-top: 0px!important;}*/
</style>
<!--end Adidas Takeover Lite -->

</head>
<?php
genesis_markup( array(
	'html5'   => '<body %s>',
	'xhtml'   => sprintf( '<body class="%s">', implode( ' ', get_body_class() ) ),
	'context' => 'body',
) );
do_action( 'genesis_before' );

genesis_markup( array(
	'html5'   => '<div %s>',
	'xhtml'   => '<div id="wrap">',
	'context' => 'site-container',
) );

do_action( 'genesis_before_header' );
do_action( 'genesis_header' );
do_action( 'genesis_after_header' );

genesis_markup( array(
	'html5'   => '<div %s>',
	'xhtml'   => '<div id="inner">',
	'context' => 'site-inner',
) );
genesis_structural_wrap( 'site-inner' );
