<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* Output primary sidebar structure
genesis_markup( array(
	'html5'   => '<aside %s>',
	'xhtml'   => '<div id="sidebar" class="sidebar widget-area">',
	'context' => 'sidebar-primary',
) );
?>

<?php

			// Restore the $wp_query to the original main query
			wp_reset_query();

			// We need to get the top-level category so we know which template to load.
		 	$get_cat = $wp_query->query['product_cat'];

		 	// The post information from the parent
		 	$post = $wp_query->post;
		 	$postID = $post->ID;

		 	// Will show the 'top' category only
		 	$category = get_the_category( $postID );
			$catName = $category[0]->cat_name;
			echo "<!-- Cat Name: ".$catName."-->";



		?>
<!-- Woven 300x250 Top Unit -->
<?php include_once( TEMPLATEPATH . '/DFP/ad-300x250_TOP.php'); ?>
<!--.end Woven 300x250 Top Unit -->

<?php

do_action( 'genesis_before_sidebar_widget_area' );
do_action( 'genesis_sidebar' );
do_action( 'genesis_after_sidebar_widget_area' );

genesis_markup( array(
	'html5' => '</aside>', //* end .sidebar-primary
	'xhtml' => '</div>', //* end #sidebar
) );
