<?php
/**
 * Theme Demos
 *
 * @package Authentic WordPress Theme
 * @subpackage Demo Import
 * @since Authentic 2.0.0
 * @version 1.0.0
 */

/**
 * Theme Demos
 */
function csco_theme_demos() {
	$demos = array(
		// Theme mods imported with every demo.
		'common_mods' => array(
			'footer_instagram_username' => 'mrporterlive',
			),
		// Specific demos.
		'demos' => array(
			'default' => array(
				'name' => esc_html( 'Demo 1', 'authentic' ),
				'preview_image_url' => '/images/demo-01.jpg',
				'mods' => array(
					'home_slider'           => true,
					'home_slider_source'    => 'featured',
					'home_carousel'         => true,
					'home_carousel_orderby' => 'views',
					'layout_archive_type'   => 'masonry',
					'layout_thumbnail_size' => 'md',
					),
				),
			'2' => array(
				'name' => esc_html( 'Demo 2', 'authentic' ),
				'preview_image_url' => '/images/demo-02.jpg',
				'mods' => array(
					'home_slider'            => true,
					'home_slider_type'       => 'large',
					'home_slider_source'     => 'featured',
					'layout_archive_type'    => 'masonry',
					'layout_thumbnail_size'  => 'md',
					'layout_columns'         => '3',
					'layout_first_post'      => false,
					'layout_width'           => '1600px',
					'layout_pagination_type' => 'ajax',
					),
				),
			'3' => array(
				'name' => esc_html( 'Demo 3', 'authentic' ),
				'preview_image_url' => '/images/demo-03.jpg',
				'mods' => array(
					'home_slider'             => true,
					'home_slider_type'        => 'multiple',
					'home_slider_height'      => '500px',
					'home_slider_visible'     => '3',
					'home_slider_padding'     => '30px',
					'home_slider_heading'     => array( 'font-size' => '2rem' ),
					'home_carousel'           => true,
					'home_carousel_orderby'   => 'views',
					'home_carousel_columns'   => '6',
					'home_carousel_heading'   => array( 'font-size' => '1rem', 'letter-spacing' => '-0.05rem' ),
					'home_carousel_thumbnail' => 'sm-sq',
					'layout_archive_type'     => 'list',
					'layout_thumbnail_size'   => 'md-ver',
					'layout_first_post'       => false,
					'layout_more_button'      => false,
					'layout_widgets'          => true,
					'layout_widgets_repeat'   => true,
					'layout_widgets_after'    => 4,
					),
				),
			'4' => array(
				'name' => esc_html( 'Demo 4', 'authentic' ),
				'preview_image_url' => '/images/demo-04.jpg',
				'query_args' => array( 'posts_per_page' => 12 ),
				'mods' => array(
					'home_carousel'           => true,
					'home_carousel_orderby'   => 'views',
					'home_carousel_columns'   => '2',
					'home_carousel_heading'   => array( 'font-size' => '2rem' ),
					'home_carousel_thumbnail' => 'md-sq',
					'home_carousel_title'     => '',
					'layout'                  => 'layout-fullwidth',
					'layout_archive_type'     => 'grid',
					'layout_columns'          => '2',
					'layout_thumbnail_size'   => 'md-sq',
					'layout_first_post'       => false,
					'layout_summary'          => false,
					'layout_more_button'      => false,
					),
				),
			'5' => array(
				'name' => esc_html( 'Demo 5', 'authentic' ),
				'preview_image_url' => '/images/demo-05.jpg',
				'mods' => array(
					'layout'                 => 'layout-fullwidth',
					'layout_archive_type'    => 'masonry',
					'layout_thumbnail_size'  => 'md',
					'layout_first_post'      => false,
					'layout_columns'         => '3',
					'layout_widgets'         => true,
					'layout_widgets_repeat'  => true,
					'layout_pagination_type' => 'ajax',
					),
				),
			'6' => array(
				'name' => esc_html( 'Demo 6', 'authentic' ),
				'preview_image_url' => '/images/demo-06.jpg',
				'mods' => array(
					'colors_topbar_bg_toggle_next'    => true,
					'colors_topbar_bg'                => '#111111',
					'colors_topbar_main_links'        => '#CCCCCC',
					'colors_topbar_main_links_hover'  => '#FFFFFF',
					'header_layout'                   => 'left',
					'header_content_right_select'     => 'menu',
					'header_content_right_menu'       => 'secondary',
					'header_logo_font'                => array( 'font-size' => '2rem', 'font-family' => 'Montserrat', 'font-weight' => '600', 'letter-spacing' => '-0.05rem' ),
					'navbar_search'                   => true,
					'navbar_alignment'                => 'left',
					'header_width'                    => '900px',
					'header_height'                   => '100px',
					'topbar_width'                    => '900px',
					'navbar_width'                    => '900px',
					'home_slider'                     => true,
					'home_slider_type'                => 'boxed',
					'home_slider_width'               => '1400px',
					'home_slider_height'              => '640px',
					'home_slider_heading'             => array( 'font-size' => '3.5rem', 'letter-spacing' => '-.2rem' ),
					'layout_width'                    => '900px',
					'layout'                          => 'layout-fullwidth',
					'layout_archive_type'             => 'standard',
					'layout_thumbnail_size'           => 'md-ver',
					'layout_first_post'               => false,
					),
				),
			'7' => array(
				'name' => esc_html( 'Demo 7', 'authentic' ),
				'preview_image_url' => '/images/demo-07.jpg',
				'mods' => array(
					'home_tiles'            => true,
					'home_tiles_source'     => 'featured',
					'home_tiles_layout'     => '4',
					'layout_archive_type'   => 'masonry',
					'layout_thumbnail_size' => 'md',
					'layout_first_post'     => false,
					),
				),
			'8' => array(
				'name' => esc_html( 'Demo 8', 'authentic' ),
				'preview_image_url' => '/images/demo-08.jpg',
				'mods' => array(
					'home_tiles'            => true,
					'home_tiles_source'     => 'featured',
					'home_tiles_layout'     => '3',
					'home_tiles_padding'    => '2px',
					'layout_archive_type'   => 'list',
					'layout_thumbnail_size' => 'md-ver',
					'layout_first_post'     => false,
					),
				),
			'9' => array(
				'name' => esc_html( 'Demo 9', 'authentic' ),
				'preview_image_url' => '/images/demo-09.jpg',
				'query_args' => array( 'posts_per_page' => 12 ),
				'mods' => array(
					'topbar'                  => false,
					'header'                  => false,
					'navbar_search'           => true,
					'navbar_social'           => true,
					'home_tiles'              => true,
					'home_tiles_source'       => 'featured',
					'home_tiles_layout'       => '7',
					'home_tiles_padding'      => '2px',
					'layout_archive_type'     => 'masonry',
					'layout_first_post'       => false,
					'layout_thumbnail_size'   => 'md',
					),
				),
			'10' => array(
				'name' => esc_html( 'Demo 10', 'authentic' ),
				'preview_image_url' => '/images/demo-10.jpg',
				'mods' => array(
					'home_carousel'           => true,
					'home_carousel_orderby'   => 'views',
					'home_carousel_columns'   => '6',
					'home_carousel_heading'   => array( 'font-size' => '1rem' ),
					'home_carousel_thumbnail' => 'md-sq',
					'home_carousel_title'     => 'Trending Posts',
					'layout_archive_type'     => 'grid',
					'layout_first_post'       => false,
					'layout_thumbnail_size'   => 'md-sq',
					),
				),
			'11' => array(
				'name' => esc_html( 'Demo 11', 'authentic' ),
				'preview_image_url' => '/images/demo-11.jpg',
				'mods' => array(
					'topbar'                  => false,
					'header'                  => false,
					'navbar_search'           => true,
					'navbar_social'           => true,
					'home_slider'             => true,
					'home_slider_source'      => 'featured',
					'home_slider_type'        => 'large',
					'layout'                  => 'layout-fullwidth',
					'layout_archive_type'     => 'masonry',
					'layout_width'            => '1140px',
					'layout_columns'          => '3',
					'layout_first_post'       => false,
					'layout_thumbnail_size'   => 'md',
					'layout_widgets'          => true,
					'layout_widgets_repeat'   => true,
					'layout_pagination_type'  => 'ajax',
					'layout_infinite_load'    => true,
					),
				),
			'12' => array(
				'name' => esc_html( 'Demo 12', 'authentic' ),
				'preview_image_url' => '/images/demo-12.jpg',
				'mods' => array(
					'typography_h3'           => array( 'font-size' => '2rem', 'letter-spacing' => '-0.1rem' ),
					'header_layout'           => 'logo',
					'navbar_search'           => true,
					'layout'                  => 'layout-fullwidth',
					'layout_archive_type'     => 'list',
					'layout_width'            => '940px',
					'layout_thumbnail_width'  => '6',
					'layout_thumbnail_size'   => 'md-ver',
					'layout_widgets'          => true,
					'layout_widgets_repeat'   => true,
					'layout_widgets_after'    => '4',
					'layout_pagination_type'  => 'ajax',
					),
				),
			'13' => array(
				'name' => esc_html( 'Demo 13', 'authentic' ),
				'preview_image_url' => '/images/demo-13.jpg',
				'mods' => array(
					'header_layout'           => 'logo',
					'navbar_search'           => true,
					'home_tiles'              => true,
					'home_tiles_source'       => 'featured',
					'home_tiles_layout'       => '2',
					'home_tiles_width'        => '1430px',
					'home_tiles_height'       => '600px',
					'home_tiles_parallax'     => false,
					'layout_archive_type'     => 'list',
					'layout_thumbnail_width'  => '6',
					'layout_thumbnail_size'   => 'md-sq',
					'layout_first_post'       => false,
					'layout_widgets'          => true,
					'layout_widgets_repeat'   => true,
					'layout_widgets_after'    => '4',
					'layout_pagination_type'  => 'ajax',
					),
				),
			'14' => array(
				'name' => esc_html( 'Demo 14', 'authentic' ),
				'preview_image_url' => '/images/demo-14.jpg',
				'mods' => array(
					'topbar'                         => false,
					'header'                         => false,
					'navbar_search'                  => true,
					'navbar_container'               => 'container-fluid',
					'colors_navbar_bg_toggle_next'   => true,
					'colors_navbar_bg'               => '#111111',
					'colors_navbar_main_links'       => '#CCCCCC',
					'colors_navbar_main_links_hover' => '#FFFFFF',
					'colors_navbar_borders'          => false,
					'home_tiles'                     => true,
					'home_tiles_source'              => 'category',
					'home_tiles_source_category'     => 2,
					'home_tiles_layout'              => '9',
					'home_tiles_padding'             => '15px',
					'home_tiles_container'           => 'container-fluid',
					'home_tiles_height'              => 'calc(100vh - 200px)',
					'home_tiles_parallax'            => false,
					'home_tiles_heading_primary'     => array( 'font-size' => '1.75rem', 'font-family' => 'Montserrat', 'font-weight' => '600', 'letter-spacing' => '-0.1rem', 'line-height' => 1 ),
					'layout_width'                   => '100%',
					'layout_archive_type'            => 'masonry',
					'layout_columns'                 => '3',
					'layout_thumbnail_size'          => 'md',
					'layout_first_post'              => false,
					'layout_widgets'                 => true,
					'layout_widgets_repeat'          => true,
					'layout_widgets_after'           => '4',
					'layout_pagination_type'         => 'ajax',
					'layout_infinite_load'           => true,
					),
				),
			'15' => array(
				'name' => esc_html( 'Demo 15', 'authentic' ),
				'preview_image_url' => '/images/demo-15.jpg',
				'mods' => array(
					'header_layout'           => 'logo',
					'navbar_search'           => true,
					'home_carousel'           => true,
					'home_carousel_orderby'   => 'views',
					'home_carousel_columns'   => '3',
					'home_carousel_thumbnail' => 'md-ver',
					'home_carousel_title'     => 'Right Now',
					'home_carousel_heading'   => array( 'font-size' => '1.5rem' ),
					'layout_archive_type'     => 'list',
					'layout_thumbnail_width'  => '6',
					'layout_thumbnail_size'   => 'md-sq',
					'layout_first_post'       => true,
					'layout_widgets'          => true,
					'layout_widgets_repeat'   => true,
					'layout_widgets_after'    => '4',
					),
				),
			'16' => array(
				'name' => esc_html( 'Demo 16', 'authentic' ),
				'preview_image_url' => '/images/demo-16.jpg',
				'mods' => array(
					'header_content_left_button_text' => 'Instagram',
					'header_content_left_button_icon' => 'instagram',
					'home_slider'                     => true,
					'home_slider_type'                => 'boxed',
					'home_slider_width'               => '1300px',
					'home_slider_height'              => '400px',
					'home_slider_heading'             => array( 'font-size' => '2rem' ),
					'home_carousel'                   => true,
					'home_carousel_orderby'           => 'views',
					'home_carousel_columns'           => '6',
					'home_carousel_heading'           => array( 'font-size' => '1rem', 'letter-spacing' => '-0.05rem' ),
					'home_carousel_thumbnail'         => 'sm-sq',
					'layout_archive_type'             => 'grid',
					'layout_thumbnail_size'           => 'md-hor',
					'layout_first_post'               => false,
					'layout_more_button'              => false,
					),
				),
			'17' => array(
				'name' => esc_html( 'Demo 17', 'authentic' ),
				'preview_image_url' => '/images/demo-17.jpg',
				'mods' => array(
					'home_tiles'                     => true,
					'home_tiles_source'              => 'category',
					'home_tiles_source_category'     => 2,
					'home_tiles_layout'              => '5',
					'home_tiles_padding'             => '4px',
					'home_tiles_height'              => '500px',
					'home_tiles_heading_primary'     => array( 'font-size' => '1.75rem', 'font-family' => 'Montserrat', 'font-weight' => '600', 'letter-spacing' => '-0.1rem', 'line-height' => 1 ),
					'layout_archive_type'            => 'masonry',
					'layout_thumbnail_size'          => 'md',
					'layout_first_post'              => false,
					),
				),
			'18' => array(
				'name' => esc_html( 'Demo 18', 'authentic' ),
				'preview_image_url' => '/images/demo-18.jpg',
				'mods' => array(
					'topbar_width'                => '1400px',
					'header_width'                => '1400px',
					'navbar_width'                => '1400px',
					'typography_h3'               => array( 'font-size' => '2rem', 'letter-spacing' => '-0.1rem' ),
					'home_slider'                 => true,
					'home_slider_type'            => 'center',
					'home_slider_width'           => '1370px',
					'home_slider_height'          => '600px',
					'home_slider_source'          => 'category',
					'home_slider_source_category' => 4,
					'home_slider_padding'         => '40px',
					'home_slider_heading'         => array( 'font-size' => '3rem' ),
					'home_slider_parallax'        => false,
					'layout_archive_type'         => 'masonry',
					'layout_thumbnail_size'       => 'md-ver',
					'layout_columns'              => '3',
					'layout_first_post'           => false,
					'layout'                      => 'layout-fullwidth',
					'layout_width'                => '1400px',
					'layout_widgets'              => true,
					'layout_widgets_repeat'       => true,
					'layout_widgets_after'        => '4',
					'layout_pagination_type'      => 'ajax',
					'layout_infinite_load'        => true,
					),
				),
			'19' => array(
				'name' => esc_html( 'Demo 19', 'authentic' ),
				'preview_image_url' => '/images/demo-19.jpg',
				'mods' => array(
					'effects_parallax'            => false,
					'home_carousel'               => true,
					'home_carousel_container'     => 'container-fluid',
					'home_carousel_orderby'       => 'views',
					'home_carousel_title'         => '',
					'home_carousel_columns'       => '6',
					'home_carousel_heading'       => array( 'font-size' => '1.5rem', 'letter-spacing' => '-0.15rem' ),
					'home_carousel_thumbnail'     => 'md-ver',
					'layout_archive_type'         => 'standard',
					'layout'                      => 'layout-fullwidth',
					'layout_width'                => '940px',
					'layout_widgets'              => true,
					'layout_widgets_repeat'       => true,
					'layout_widgets_after'        => '4',
					'layout_pagination_type'      => 'ajax',
					'layout_infinite_load'        => true,
					),
				),
			'20' => array(
				'name' => esc_html( 'Demo 20', 'authentic' ),
				'preview_image_url' => '/images/demo-20.jpg',
				'mods' => array(
					'home_slider'                 => true,
					'home_slider_type'            => 'boxed',
					'home_slider_width'           => '1140px',
					'home_slider_height'          => '600px',
					'home_slider_source'          => 'category',
					'home_slider_source_category' => 4,
					'home_slider_heading'         => array( 'font-size' => '2.5rem' ),
					'home_slider_parallax'        => false,
					'home_carousel'               => true,
					'home_carousel_orderby'       => 'views',
					'home_carousel_columns'       => '4',
					'home_carousel_thumbnail'     => 'md-ver',
					'effects_parallax'            => false,
					'layout_archive_type'         => 'list',
					'layout_thumbnail_size'       => 'md-ver',
					'layout_widgets'              => true,
					'layout_widgets_repeat'       => true,
					'layout_widgets_after'        => '4',
					'layout_pagination_type'      => 'ajax',
					),
				),
			),
	);
	return $demos;
}
add_filter( 'csco_theme_demos', 'csco_theme_demos' );
